---
framework:
  ConfigFileVersion: 4

  AdminMode: 0
  ApplicationName: Wifty
  AdminEmail: 'wifty@example.com'

  Database:
    Driver: SQLite
    Host: localhost
    User: postgres
    Version: 0.0.20
    Password: ''
    RequireSSL: 0
  Plugins:
    - SkeletonApp: {}
    - CompressedCSSandJS: {}
    - User: {}
    - Authentication::Password:
        login_by: email

  Mailer: IO
  MailerArgs:
    - %log/mail.log%
  SiteConfig: etc/site_config.yml

  Web:
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
application:
#  RequireAuth: 1
  WikiName: A Wiki
  Formatter: Markdown
  # The formatter options are "Markdown" and "Kwiki"
  # Logo: http://svk.bestpractical.com/svk-logo.png
  # The logo points to the url to a logo image
