framework:
  AdminMode: 0
  ApplicationName: Wifty
  #LogConfig: etc/log4perl.conf

  Web:
    Port: 80
    BaseURL: http://jifty.org
  Database:
  #  Driver: Pg
    Driver: SQLite
    Host: localhost
    User: postgres
    Version: 0.0.19
    Password: ''
    RequireSSL: 0
#  Mailer: IO
#  MailerArgs:
#    - %log/mail.log%
  SiteConfig: etc/site_config.yml
application: 
  MaxWurbles: 9
