---
framework:
  ConfigFileVersion: 4
  
  ApplicationName: Wifty
  AdminEmail: 'wifty@example.com'

  AdminMode: 0
  DevelMode: 1
  LogConfig: etc/log4perl.conf

  Database:
    Version: 0.0.24
    AutoUpgrade: 1
    CheckSchema: 1
    Driver: SQLite
    Host: localhost
    User: postgres
    Password: ''
    RequireSSL: 0

  Plugins:
    - CompressedCSSandJS: {}
    - User: {}
    - Authentication::Password:
        login_by: email
    - ViewDeclarePage: {}

  Mailer: IO
  MailerArgs:
    - %log/mail.log%
  SiteConfig: etc/site_config.yml

  L10N: 
    PoDir: share/po

  View: 
    FallbackHandler: Jifty::View::Declare::Handler
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler

  Web:
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
application:
  # name of this wiki
  WikiName: A Wiki

  # can anonymous users change wiki?
  RequireAuth: 1

  # The formatter options are "Markdown" and "Kwiki"
  Formatter: Markdown

  # The logo points to the url to a logo image
  # Logo: http://www.bestpractical.com/images/svk-logo.png
