framework:
  AdminMode: 0
  ApplicationName: Wifty
  AdminEmail: 'wifty@example.com'

  Database:
    Driver: SQLite
    Host: localhost
    User: postgres
    Version: 0.0.20
    Password: ''
    RequireSSL: 0
  Plugins:
    - Login: {}
  Mailer: SMTP
  MailerArgs: ['69.17.117.59']
#  MailerArgs:
#    - %log/mail.log%
  SiteConfig: etc/site_config.yml

  Web:
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
application:
#  RequireAuth: 1
  WikiName: A Wiki
