framework:
  AdminMode: 0
  ApplicationName: Wifty

  Web:
    Port: 80
    BaseURL: http://jifty.org
  Database:
    Driver: SQLite
    Host: localhost
    User: postgres
    Version: 0.0.19
    Password: ''
    RequireSSL: 0
#  Mailer: IO
#  MailerArgs:
#    - %log/mail.log%
  SiteConfig: etc/site_config.yml
application: 
  MaxWurbles: 9
