---
framework:
  ConfigFileVersion: 4

  AdminMode: 0
  ApplicationName: Wifty
  AdminEmail: 'wifty@example.com'

  Database:
    Driver: SQLite
    Host: localhost
    User: postgres
    Version: 0.0.20
    Password: ''
    RequireSSL: 0
  Plugins:
    - SkeletonApp: {}
    - CompressedCSSandJS: {}
    - User: {}
    - Authentication::Password:
        login_by: email
    - ViewDeclarePage: {}

  Mailer: IO
  MailerArgs:
    - %log/mail.log%
  SiteConfig: etc/site_config.yml

  Web:
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
application:
  # name of this wiki
  WikiName: A Wiki

  # can anonymous users change wiki?
  RequireAuth: 1

  # The formatter options are "Markdown" and "Kwiki"
  Formatter: Markdown

  # The logo points to the url to a logo image
  # Logo: http://www.bestpractical.com/images/svk-logo.png
